#.travis.yml

language: android
sudo: false

node_js:
  - "8.11"
  
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-26

branches:
  only:
  - master

before_install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install nodejs

install:
  - npm install

script:
  - node node_modules/cordova/bin/cordova prepare
  - node node_modules/cordova/bin/cordova build android
