#.travis.yml

language: android

node_js:
  - "8.11"
  
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.3
    - android-26

-sudo: false

branches:
  only:
  - master

before_install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install nodejs
  - sudo npm install -g cordova

install:
  - npm install

script:
  - cordova prepare
  - cordova build android
