#.travis.yml

language: android

node_js:
  - "8.11"

sudo: false

branches:
  only:
  - master

before_install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install nodejs

install:
  - npm cache clean
  - npm install
  - echo y | android update sdk -u --filter android-24

script:
  - npm run build
  
release:
  - exit 0  